import { createRouter, createWebHashHistory } from 'vue-router'
import Layout from '@/views/layout/Layout.vue'
import type { RouteRecordExt } from '@/types/router'

export const constantRouterMap: RouteRecordExt[] = [
  { path: '/404', component: () => import('@/views/normal/404/index.vue'), hidden: true },
  { path: '/login', component: () => import('@/views/normal/login/index.vue'), hidden: true },
  {
    path: '',
    component: Layout,
    redirect: '/home',
    meta: { title: '首页', icon: 'home' },
    children: [
      {
        path: 'home',
        name: 'home',
        component: () => import('@/views/home/index.vue'),
        meta: { title: '首页', icon: 'dashboard' },
      },
      {
        name: 'document',
        path: 'https://www.macrozheng.com',
        component: () => import('@/views/normal/link/index.vue'),
        meta: { title: '学习教程', icon: 'document' },
      },
      {
        name: 'video',
        path: 'https://www.macrozheng.com/mall/foreword/mall_video.html',
        component: () => import('@/views/normal/link/index.vue'),
        meta: { title: '视频教程', icon: 'video' },
      },
      // {
      //   path: 'test',
      //   name: 'test',
      //   component: () => import('@/views/test/index.vue'),
      //   meta: { title: '组件测试', icon: 'product-cate' },
      // },
    ],
  },
]

export const asyncRouterMap: RouteRecordExt[] = [
  {
    path: '/pms',
    component: Layout,
    redirect: '/pms/product',
    name: 'pms',
    meta: { title: '商品', icon: 'product' },
    children: [
      {
        path: 'product',
        name: 'product',
        component: () => import('@/views/pms/product/index.vue'),
        meta: { title: '商品列表', icon: 'product-list' },
      },
      {
        path: 'addProduct',
        name: 'addProduct',
        component: () => import('@/views/pms/product/add.vue'),
        meta: { title: '添加商品', icon: 'product-add' },
      },
      {
        path: 'updateProduct',
        name: 'updateProduct',
        component: () => import('@/views/pms/product/update.vue'),
        meta: { title: '修改商品', icon: 'product-add' },
        hidden: true,
      },
      {
        path: 'productCate',
        name: 'productCate',
        component: () => import('@/views/pms/productCate/index.vue'),
        meta: { title: '商品分类', icon: 'product-cate' },
      },
      {
        path: 'addProductCate',
        name: 'addProductCate',
        component: () => import('@/views/pms/productCate/add.vue'),
        meta: { title: '添加商品分类' },
        hidden: true,
      },
      {
        path: 'updateProductCate',
        name: 'updateProductCate',
        component: () => import('@/views/pms/productCate/update.vue'),
        meta: { title: '修改商品分类' },
        hidden: true,
      },
      {
        path: 'productAttr',
        name: 'productAttr',
        component: () => import('@/views/pms/productAttr/index.vue'),
        meta: { title: '商品类型', icon: 'product-attr' },
      },
      {
        path: 'productAttrList',
        name: 'productAttrList',
        component: () => import('@/views/pms/productAttr/productAttrList.vue'),
        meta: { title: '商品属性列表' },
        hidden: true,
      },
      {
        path: 'addProductAttr',
        name: 'addProductAttr',
        component: () => import('@/views/pms/productAttr/addProductAttr.vue'),
        meta: { title: '添加商品属性' },
        hidden: true,
      },
      {
        path: 'updateProductAttr',
        name: 'updateProductAttr',
        component: () => import('@/views/pms/productAttr/updateProductAttr.vue'),
        meta: { title: '修改商品属性' },
        hidden: true,
      },
      {
        path: 'brand',
        name: 'brand',
        component: () => import('@/views/pms/brand/index.vue'),
        meta: { title: '品牌管理', icon: 'product-brand' },
      },
      {
        path: 'addBrand',
        name: 'addBrand',
        component: () => import('@/views/pms/brand/add.vue'),
        meta: { title: '添加品牌' },
        hidden: true,
      },
      {
        path: 'updateBrand',
        name: 'updateBrand',
        component: () => import('@/views/pms/brand/update.vue'),
        meta: { title: '编辑品牌' },
        hidden: true,
      },
    ],
  },
  {
    path: '/oms',
    component: Layout,
    redirect: '/oms/order',
    name: 'oms',
    meta: { title: '订单', icon: 'order' },
    children: [
      {
        path: 'order',
        name: 'order',
        component: () => import('@/views/oms/order/index.vue'),
        meta: { title: '订单列表', icon: 'product-list' },
      },
      {
        path: 'orderDetail',
        name: 'orderDetail',
        component: () => import('@/views/oms/order/orderDetail.vue'),
        meta: { title: '订单详情' },
        hidden: true,
      },
      {
        path: 'deliverOrderList',
        name: 'deliverOrderList',
        component: () => import('@/views/oms/order/deliverOrderList.vue'),
        meta: { title: '发货列表' },
        hidden: true,
      },
      {
        path: 'orderSetting',
        name: 'orderSetting',
        component: () => import('@/views/oms/order/setting.vue'),
        meta: { title: '订单设置', icon: 'order-setting' },
      },
      {
        path: 'returnApply',
        name: 'returnApply',
        component: () => import('@/views/oms/apply/index.vue'),
        meta: { title: '售后管理', icon: 'order-return' },
      },
      {
        path: 'refund',
        name: 'refund',
        component: () => import('@/views/oms/refund/index.vue'),
        meta: { title: '退款管理', icon: 'order-return' },
      },
      {
        path: 'supportTicket',
        name: 'supportTicket',
        component: () => import('@/views/oms/support/index.vue'),
        meta: { title: '工单中心', icon: 'order-return' },
      },
      {
        path: 'returnReason',
        name: 'returnReason',
        component: () => import('@/views/oms/apply/reason.vue'),
        meta: { title: '售后原因设置', icon: 'order-return-reason' },
      },
      {
        path: 'returnApplyDetail',
        name: 'returnApplyDetail',
        component: () => import('@/views/oms/apply/applyDetail.vue'),
        meta: { title: '售后详情' },
        hidden: true,
      },
    ],
  },
  {
    path: '/caseOps',
    component: Layout,
    redirect: '/caseOps/caseLab',
    name: 'caseOps',
    meta: { title: '实验与评测', icon: 'example' },
    children: [
      {
        path: 'caseLab',
        name: 'caseLab',
        component: () => import('@/views/caseOps/caseLab/index.vue'),
        meta: { title: '故障注入实验室', icon: 'example' },
      },
      {
        path: 'agentEval',
        name: 'agentEval',
        component: () => import('@/views/caseOps/agentEval/index.vue'),
        meta: { title: 'Agent离线评测', icon: 'code' },
      },
      {
        path: 'agentOps',
        name: 'agentOps',
        component: () => import('@/views/caseOps/agentOps/index.vue'),
        meta: { title: '智能代理在线监控', icon: 'monitor' },
      },
    ],
  },
  {
    path: '/sms',
    component: Layout,
    redirect: '/sms/coupon',
    name: 'sms',
    meta: { title: '营销', icon: 'sms' },
    children: [
      {
        path: 'flash',
        name: 'flash',
        component: () => import('@/views/sms/flash/index.vue'),
        meta: { title: '秒杀活动列表', icon: 'sms-flash' },
      },
      {
        path: 'flashSession',
        name: 'flashSession',
        component: () => import('@/views/sms/flash/sessionList.vue'),
        meta: { title: '秒杀时间段列表' },
        hidden: true,
      },
      {
        path: 'selectSession',
        name: 'selectSession',
        component: () => import('@/views/sms/flash/selectSessionList.vue'),
        meta: { title: '秒杀时间段选择' },
        hidden: true,
      },
      {
        path: 'flashProductRelation',
        name: 'flashProductRelation',
        component: () => import('@/views/sms/flash/productRelationList.vue'),
        meta: { title: '秒杀商品列表' },
        hidden: true,
      },
      {
        path: 'coupon',
        name: 'coupon',
        component: () => import('@/views/sms/coupon/index.vue'),
        meta: { title: '优惠券列表', icon: 'sms-coupon' },
      },
      {
        path: 'addCoupon',
        name: 'addCoupon',
        component: () => import('@/views/sms/coupon/add.vue'),
        meta: { title: '添加优惠券' },
        hidden: true,
      },
      {
        path: 'updateCoupon',
        name: 'updateCoupon',
        component: () => import('@/views/sms/coupon/update.vue'),
        meta: { title: '修改优惠券' },
        hidden: true,
      },
      {
        path: 'couponHistory',
        name: 'couponHistory',
        component: () => import('@/views/sms/coupon/history.vue'),
        meta: { title: '优惠券领取详情' },
        hidden: true,
      },
      {
        path: 'brand',
        name: 'homeBrand',
        component: () => import('@/views/sms/brand/index.vue'),
        meta: { title: '品牌推荐', icon: 'product-brand' },
      },
      {
        path: 'new',
        name: 'homeNew',
        component: () => import('@/views/sms/new/index.vue'),
        meta: { title: '新品推荐', icon: 'sms-new' },
      },
      {
        path: 'hot',
        name: 'homeHot',
        component: () => import('@/views/sms/hot/index.vue'),
        meta: { title: '人气推荐', icon: 'sms-hot' },
      },
      {
        path: 'subject',
        name: 'homeSubject',
        component: () => import('@/views/sms/subject/index.vue'),
        meta: { title: '专题推荐', icon: 'sms-subject' },
      },
      {
        path: 'advertise',
        name: 'homeAdvertise',
        component: () => import('@/views/sms/advertise/index.vue'),
        meta: { title: '广告列表', icon: 'sms-ad' },
      },
      {
        path: 'addAdvertise',
        name: 'addHomeAdvertise',
        component: () => import('@/views/sms/advertise/add.vue'),
        meta: { title: '添加广告' },
        hidden: true,
      },
      {
        path: 'updateAdvertise',
        name: 'updateHomeAdvertise',
        component: () => import('@/views/sms/advertise/update.vue'),
        meta: { title: '编辑广告' },
        hidden: true,
      },
    ],
  },
  {
    path: '/ums',
    component: Layout,
    redirect: '/ums/admin',
    name: 'ums',
    meta: { title: '权限', icon: 'ums' },
    children: [
      {
        path: 'admin',
        name: 'admin',
        component: () => import('@/views/ums/admin/index.vue'),
        meta: { title: '用户列表', icon: 'ums-admin' },
      },
      {
        path: 'role',
        name: 'role',
        component: () => import('@/views/ums/role/index.vue'),
        meta: { title: '角色列表', icon: 'ums-role' },
      },
      {
        path: 'allocMenu',
        name: 'allocMenu',
        component: () => import('@/views/ums/role/allocMenu.vue'),
        meta: { title: '分配菜单' },
        hidden: true,
      },
      {
        path: 'allocResource',
        name: 'allocResource',
        component: () => import('@/views/ums/role/allocResource.vue'),
        meta: { title: '分配资源' },
        hidden: true,
      },
      {
        path: 'menu',
        name: 'menu',
        component: () => import('@/views/ums/menu/index.vue'),
        meta: { title: '菜单列表', icon: 'ums-menu' },
      },
      {
        path: 'addMenu',
        name: 'addMenu',
        component: () => import('@/views/ums/menu/add.vue'),
        meta: { title: '添加菜单' },
        hidden: true,
      },
      {
        path: 'updateMenu',
        name: 'updateMenu',
        component: () => import('@/views/ums/menu/update.vue'),
        meta: { title: '修改菜单' },
        hidden: true,
      },
      {
        path: 'resource',
        name: 'resource',
        component: () => import('@/views/ums/resource/index.vue'),
        meta: { title: '资源列表', icon: 'ums-resource' },
      },
      {
        path: 'resourceCategory',
        name: 'resourceCategory',
        component: () => import('@/views/ums/resource/categoryList.vue'),
        meta: { title: '资源分类' },
        hidden: true,
      },
    ],
  },
  {
    path: '/sys',
    component: Layout,
    redirect: '/sys/dict',
    name: 'sys',
    meta: { title: '系统管理', icon: 'sys' },
    children: [
      {
        path: 'dict',
        name: 'dict',
        component: () => import('@/views/sys/dict/index.vue'),
        meta: { title: '字典管理', icon: 'dict' },
      },
      {
        path: 'dept',
        name: 'dept',
        component: () => import('@/views/sys/dept/index.vue'),
        meta: { title: '部门管理', icon: 'dept' },
      },
      {
        path: 'post',
        name: 'post',
        component: () => import('@/views/sys/post/index.vue'),
        meta: { title: '岗位管理', icon: 'post' },
      },
      {
        path: 'file',
        name: 'file',
        component: () => import('@/views/sys/file/index.vue'),
        meta: { title: '文件中心', icon: 'file' },
      },
    ],
  },
  {
    path: '/job',
    component: Layout,
    redirect: '/job/jobCenter',
    name: 'job',
    meta: { title: '任务中心', icon: 'job' },
    children: [
      {
        path: 'jobCenter',
        name: 'jobCenter',
        component: () => import('@/views/job/index.vue'),
        meta: { title: '任务中心', icon: 'job' },
      },
    ],
  },
  {
    path: '/member',
    component: Layout,
    redirect: '/member/tag',
    name: 'member',
    meta: { title: '会员运营', icon: 'member' },
    children: [
      {
        path: 'tag',
        name: 'memberTag',
        component: () => import('@/views/member/tag/index.vue'),
        meta: { title: '会员标签', icon: 'tag' },
      },
      {
        path: 'level',
        name: 'memberLevelUpgrade',
        component: () => import('@/views/member/level/index.vue'),
        meta: { title: '等级升级', icon: 'level' },
      },
    ],
  },
  {
    path: '/trade',
    component: Layout,
    redirect: '/trade/express',
    name: 'trade',
    meta: { title: '交易支撑', icon: 'trade' },
    children: [
      {
        path: 'express',
        name: 'expressCompany',
        component: () => import('@/views/trade/express/index.vue'),
        meta: { title: '快递公司', icon: 'express' },
      },
      {
        path: 'freight',
        name: 'freightTemplate',
        component: () => import('@/views/trade/freight/index.vue'),
        meta: { title: '运费模板', icon: 'freight' },
      },
      {
        path: 'pickup',
        name: 'pickupPoint',
        component: () => import('@/views/trade/pickup/index.vue'),
        meta: { title: '自提点', icon: 'pickup' },
      },
      {
        path: 'pickupCode',
        name: 'pickupCode',
        component: () => import('@/views/trade/pickupCode/index.vue'),
        meta: { title: '核销码', icon: 'code' },
      },
    ],
  },
  {
    path: '/marketing',
    component: Layout,
    redirect: '/marketing/limitDiscount',
    name: 'marketing',
    meta: { title: '营销活动', icon: 'marketing' },
    children: [
      {
        path: 'limitDiscount',
        name: 'limitDiscount',
        component: () => import('@/views/marketing/limitDiscount/index.vue'),
        meta: { title: '限时折扣', icon: 'discount' },
      },
      {
        path: 'fullReduction',
        name: 'fullReduction',
        component: () => import('@/views/marketing/fullReduction/index.vue'),
        meta: { title: '满减送', icon: 'reduction' },
      },
      {
        path: 'groupon',
        name: 'groupon',
        component: () => import('@/views/marketing/groupon/index.vue'),
        meta: { title: '拼团', icon: 'groupon' },
      },
      {
        path: 'bargain',
        name: 'bargain',
        component: () => import('@/views/marketing/bargain/index.vue'),
        meta: { title: '砍价', icon: 'bargain' },
      },
      {
        path: 'diy',
        name: 'diyPage',
        component: () => import('@/views/marketing/diy/index.vue'),
        meta: { title: '装修页', icon: 'diy' },
      },
    ],
  },
  {
    path: '/statistics',
    component: Layout,
    redirect: '/statistics/report',
    name: 'statistics',
    meta: { title: '统计报表', icon: 'statistics' },
    children: [
      {
        path: 'report',
        name: 'statisticsReport',
        component: () => import('@/views/statistics/index.vue'),
        meta: { title: '统计报表', icon: 'statistics' },
      },
    ],
  },
  {
    path: '/log',
    component: Layout,
    redirect: '/log/audit',
    name: 'log',
    meta: { title: '日志审计', icon: 'log' },
    children: [
      {
        path: 'audit',
        name: 'logAudit',
        component: () => import('@/views/log/index.vue'),
        meta: { title: '日志审计', icon: 'log' },
      },
    ],
  },
  {
    path: '/pay',
    component: Layout,
    redirect: '/pay/order',
    name: 'pay',
    meta: { title: '支付管理', icon: 'pay' },
    children: [
      {
        path: 'order',
        name: 'payOrder',
        component: () => import('@/views/pay/order/index.vue'),
        meta: { title: '支付单', icon: 'payOrder' },
      },
      {
        path: 'notify',
        name: 'payNotifyTask',
        component: () => import('@/views/pay/notify/index.vue'),
        meta: { title: '回调任务', icon: 'pay' },
      },
    ],
  },
]

// createWebHistory（History 模式）地址格式（需要服务器配置）：http://domain.com/admin/home
// createWebHashHistory（Hash 模式）地址格式（会多带一个#号）：http://domain.com/admin/#/home
const router = createRouter({
  history: createWebHashHistory(),
  routes: constantRouterMap,
})

export default router
